// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzxwytnwcmhesyxkiyzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6eHd5dG53Y21oZXN5eGtpeXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjY5OTgsImV4cCI6MjA2OTEwMjk5OH0.6Tcm9YQ9UK7mfEAzQm9HC41uGqo8CVOugljC6iKuETc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});